### ISSUE TITLE
Make use of toStrict from Data.ByteString.Lazy ?

### ISSUE THREAD

**Issue by xaverdh** [jtdaugherty/HaskellNet#44]
Is there a reason why lazyToStrict in Network/HaskellNet/SMTP.hs does not simply use toStrict from Data.ByteString.Lazy ? As far as I can see, toStrict it is meant exactly for this purpose, and it does seem to help performance a bit (disclaimer: I did not do any real benchmarks, just judging from my use case).

**Comment by jtdaugherty** [comment]
In all likelihood the original author either didn't know about this or it wasn't available at the time. Either way, thanks for the patch!
