### ISSUE TITLE
Do not use the now-removed `Network` module

### ISSUE THREAD

**Issue by ygale** [jtdaugherty/HaskellNet#49]
`HaskellNet` currently uses the function `connectTo`, from the `Network` module in the `network` library, to create its TCP connections.

In the `network` library, the `Network` module has long been deprecated. The docs say to use `Network.Socket` instead. Now the `Network` module has been removed, beginning with version 3.0.0.0 released in January 2019 (latest version is 3.0.0.1). It will soon become very difficult to compile `HaskellNet` in any up-to-date Haskell environment.

As an immediate stop-gap, please add a `network < 3.0.0.0` constraint to avoid build failures. Then please switch to using `Network.Socket` (or some other well-maintained networking library) to create the connections.

EDIT: Sorry, the `Network` module was not actually removed until 3.0.0.0, in January 2019. It's just that the haddocks stopped building in 2.7.0.0. But now it is gone altogether. Version numbers fixed.

**Comment by ygale** [comment]
Another option would be to use Vincent Hanquez's [connection](https://hackage.haskell.org/package/connection) library. That's what [HaskellNet-SSL](https://hackage.haskell.org/package/HaskellNet-SSL) does.

**Comment by jtdaugherty** [comment]
Thanks for the patch!

As for as `connection` is concerned, I would definitely avoid that due to its problematic dependencies, but as I am not maintaining this library (and have sought maintainers in the past) my opinion about `connection` will potentially be moot if someone else wants to take over. :)

**Comment by ygale** [comment]
@jtdaugherty Yes, although `connection` would make the fix trivial, the additional dependencies are an issue. Probably most people are using `HakellNet-SSL` nowadays, with this library just a dependency, so they are anyway already building `connection` and its dependencies. But no problem, we can use `Network.Socket`.
